graph LR
x00 & y00 --> AND0{AND}:::and --> gsv
x00 & y00 --> XOR0{XOR}:::xor --> z00:::output
x01 & y01 --> AND1{AND}:::and --> wcd
x01 & y01 --> XOR1{XOR}:::xor --> qtg
x02 & y02 --> AND2{AND}:::and --> hjk
x02 & y02 --> XOR2{XOR}:::xor --> vgg
x04 & y04 --> AND3{AND}:::and --> wmc
x05 & y05 --> XOR3{XOR}:::xor --> pjv
x06 & y06 --> AND4{AND}:::and --> kcg
x06 & y06 --> XOR4{XOR}:::xor --> fgk
x07 & y07 --> AND5{AND}:::and --> hhm
x09 & y09 --> XOR5{XOR}:::xor --> ghk
x10 & y10 --> XOR6{XOR}:::xor --> vjd
x11 & y11 --> XOR7{XOR}:::xor --> mws
x12 & y12 --> AND6{AND}:::and --> knv
x12 & y12 --> XOR8{XOR}:::xor --> dmv
x15 & y15 --> AND7{AND}:::and --> rbm
x15 & y15 --> XOR9{XOR}:::xor --> jfh
x17 & y17 --> AND8{AND}:::and --> pjm
x18 & y18 --> AND9{AND}:::and --> mjf
x18 & y18 --> XOR10{XOR}:::xor --> brn
x20 & y20 --> AND10{AND}:::and --> mmk
x20 & y20 --> XOR11{XOR}:::xor --> pwm
x21 & y21 --> AND11{AND}:::and --> swk
x22 & y22 --> AND12{AND}:::and --> hcv
x23 & y23 --> XOR12{XOR}:::xor --> crb
x25 & y25 --> XOR13{XOR}:::xor --> rjv
x26 & y26 --> AND13{AND}:::and --> jvj
x26 & y26 --> XOR14{XOR}:::xor --> stc
x27 & y27 --> AND14{AND}:::and --> wqf
x28 & y28 --> AND15{AND}:::and --> mdr
x28 & y28 --> XOR15{XOR}:::xor --> shq
x29 & y29 --> AND16{AND}:::and --> shs
x32 & y32 --> XOR16{XOR}:::xor --> pqv
x33 & y33 --> XOR17{XOR}:::xor --> shg
x34 & y34 --> XOR18{XOR}:::xor --> mhc
x35 & y35 --> XOR19{XOR}:::xor --> rpq
x37 & y37 --> AND17{AND}:::and --> gnn
x37 & y37 --> XOR20{XOR}:::xor --> ftt
x38 & y38 --> AND18{AND}:::and --> qjd
x38 & y38 --> XOR21{XOR}:::xor --> dhm
x40 & y40 --> AND19{AND}:::and --> kqh
x40 & y40 --> XOR22{XOR}:::xor --> tqg
x41 & y41 --> AND20{AND}:::and --> mqp
x42 & y42 --> AND21{AND}:::and --> gqq
x42 & y42 --> XOR23{XOR}:::xor --> msd
x43 & y43 --> AND22{AND}:::and --> dkq
x44 & y44 --> AND23{AND}:::and --> jdh
y03 & x03 --> AND24{AND}:::and --> tqj
y03 & x03 --> XOR24{XOR}:::xor --> fbp
y04 & x04 --> XOR25{XOR}:::xor --> pbn
y05 & x05 --> AND25{AND}:::and --> vfm
y07 & x07 --> XOR26{XOR}:::xor --> stn
y08 & x08 --> AND26{AND}:::and --> z08:::output
y08 & x08 --> XOR27{XOR}:::xor --> dnc
y09 & x09 --> AND27{AND}:::and --> btq
y10 & x10 --> AND28{AND}:::and --> fkq
y11 & x11 --> AND29{AND}:::and --> bbv
y13 & x13 --> AND30{AND}:::and --> qmc
y13 & x13 --> XOR28{XOR}:::xor --> kph
y14 & x14 --> AND31{AND}:::and --> vjh
y14 & x14 --> XOR29{XOR}:::xor --> sdn
y16 & x16 --> AND32{AND}:::and --> dwj
y16 & x16 --> XOR30{XOR}:::xor --> btj
y17 & x17 --> XOR31{XOR}:::xor --> fhk
y19 & x19 --> AND33{AND}:::and --> stp
y19 & x19 --> XOR32{XOR}:::xor --> mgr
y21 & x21 --> XOR33{XOR}:::xor --> mpm
y22 & x22 --> XOR34{XOR}:::xor --> hrj
y23 & x23 --> AND34{AND}:::and --> jmr
y24 & x24 --> AND35{AND}:::and --> ccq
y24 & x24 --> XOR35{XOR}:::xor --> jjh
y25 & x25 --> AND36{AND}:::and --> ctp
y27 & x27 --> XOR36{XOR}:::xor --> hqw
y29 & x29 --> XOR37{XOR}:::xor --> kdn
y30 & x30 --> AND37{AND}:::and --> nmd
y30 & x30 --> XOR38{XOR}:::xor --> tdc
y31 & x31 --> AND38{AND}:::and --> tnf
y31 & x31 --> XOR39{XOR}:::xor --> mbc
y32 & x32 --> AND39{AND}:::and --> jbc
y33 & x33 --> AND40{AND}:::and --> qpq
y34 & x34 --> AND41{AND}:::and --> fgq
y35 & x35 --> AND42{AND}:::and --> rkm
y36 & x36 --> AND43{AND}:::and --> jwh
y36 & x36 --> XOR40{XOR}:::xor --> fjc
y39 & x39 --> AND44{AND}:::and --> gtf
y39 & x39 --> XOR41{XOR}:::xor --> vnc
y41 & x41 --> XOR42{XOR}:::xor --> jhb
y43 & x43 --> XOR43{XOR}:::xor --> vfw
y44 & x44 --> XOR44{XOR}:::xor --> spg
bmh & tqj --> OR0{OR}:::or --> mhs
bqf & vnc --> AND45{AND}:::and --> jjt
bqf & vnc --> XOR45{XOR}:::xor --> z39:::output
brn & jpj --> AND46{AND}:::and --> srr
btj & tmm --> AND47{AND}:::and --> z16:::output
btj & tmm --> XOR46{XOR}:::xor --> mrb
btq & kgf --> OR1{OR}:::or --> kmb
ccq & hns --> OR2{OR}:::or --> vdt
cgp & vjh --> OR3{OR}:::or --> gjd
ckj & jjh --> AND48{AND}:::and --> hns
ckj & jjh --> XOR47{XOR}:::xor --> z24:::output
cpp & tnf --> OR4{OR}:::or --> kcv
crb & gqd --> AND49{AND}:::and --> fpk
crb & gqd --> XOR48{XOR}:::xor --> z23:::output
crw & bbv --> OR5{OR}:::or --> wvt
ctp & mdt --> OR6{OR}:::or --> nqv
dbc & kqh --> OR7{OR}:::or --> tkw
dhm & bgj --> OR8{OR}:::or --> bqf
djd & wqf --> OR9{OR}:::or --> msp
dkn & mws --> AND50{AND}:::and --> crw
dkn & mws --> XOR49{XOR}:::xor --> z11:::output
dmv & wvt --> AND51{AND}:::and --> tkv
dmv & wvt --> XOR50{XOR}:::xor --> z12:::output
dnc & rtp --> XOR51{XOR}:::xor --> cdj
dpv & mgr --> AND52{AND}:::and --> fvd
dpv & mgr --> XOR52{XOR}:::xor --> z19:::output
dwj & mrb --> OR10{OR}:::or --> wkh
ffg & stn --> XOR53{XOR}:::xor --> z07:::output
fgk & jbp --> AND53{AND}:::and --> rdf
fgk & jbp --> XOR54{XOR}:::xor --> z06:::output
fhk & wkh --> AND54{AND}:::and --> vpv
fkq & qfs --> OR11{OR}:::or --> dkn
fpk & jmr --> OR12{OR}:::or --> ckj
ftt & hwf --> XOR55{XOR}:::xor --> z37:::output
fvk & kdn --> AND55{AND}:::and --> kvv
gbg & vgg --> AND56{AND}:::and --> qfv
gbg & vgg --> XOR56{XOR}:::xor --> z02:::output
gfm & shg --> XOR57{XOR}:::xor --> z33:::output
ghk & pnr --> XOR58{XOR}:::xor --> z09:::output
gjd & jfh --> AND57{AND}:::and --> bjj
gnn & qmd --> OR13{OR}:::or --> kvn
gqq & nnk --> OR14{OR}:::or --> stv
gsv & qtg --> AND58{AND}:::and --> vjb
gsv & qtg --> XOR59{XOR}:::xor --> z01:::output
gtf & jjt --> OR15{OR}:::or --> dfv
gtm & mqp --> OR16{OR}:::or --> tfr
gtn & mpm --> AND59{AND}:::and --> dgd
hcv & wfs --> OR17{OR}:::or --> gqd
hqw & jmq --> AND60{AND}:::and --> djd
hqw & jmq --> XOR60{XOR}:::xor --> z27:::output
hrj & tjh --> AND61{AND}:::and --> wfs
hsq & fgq --> OR18{OR}:::or --> pfh
hwf & ftt --> AND62{AND}:::and --> qmd
jbc & mnv --> OR19{OR}:::or --> z32:::output
jdh & qrw --> OR20{OR}:::or --> z45:::output
jfh & gjd --> XOR61{XOR}:::xor --> z15:::output
jhb & tkw --> XOR62{XOR}:::xor --> z41:::output
jnn & vfm --> OR21{OR}:::or --> jbp
jpj & brn --> XOR63{XOR}:::xor --> z18:::output
jqm & fjc --> AND63{AND}:::and --> ktw
jqm & fjc --> XOR64{XOR}:::xor --> z36:::output
jrd & qmc --> OR22{OR}:::or --> hrm
jsr & kph --> XOR65{XOR}:::xor --> z13:::output
jvj & bch --> OR23{OR}:::or --> jmq
kcv & pqv --> XOR66{XOR}:::xor --> gfm
kdn & fvk --> XOR67{XOR}:::xor --> z29:::output
kmb & vjd --> AND64{AND}:::and --> qfs
knv & tkv --> OR24{OR}:::or --> jsr
kph & jsr --> AND65{AND}:::and --> jrd
ktw & jwh --> OR25{OR}:::or --> hwf
kvn & qjd --> XOR68{XOR}:::xor --> z38:::output
kvv & shs --> OR26{OR}:::or --> scp
mbc & sjk --> XOR69{XOR}:::xor --> z31:::output
mdr & dqc --> OR27{OR}:::or --> fvk
mhm & mhc --> AND66{AND}:::and --> hsq
mhm & mhc --> XOR70{XOR}:::xor --> z34:::output
mhs & pbn --> AND67{AND}:::and --> whd
mjf & srr --> OR28{OR}:::or --> dpv
mpm & gtn --> XOR71{XOR}:::xor --> z21:::output
msd & tfr --> AND68{AND}:::and --> nnk
msd & tfr --> XOR72{XOR}:::xor --> z42:::output
msp & shq --> AND69{AND}:::and --> dqc
msp & shq --> XOR73{XOR}:::xor --> z28:::output
nct & mmk --> OR29{OR}:::or --> gtn
nfk & dkq --> OR30{OR}:::or --> bfw
nmd & pkv --> OR31{OR}:::or --> sjk
nqv & stc --> XOR74{XOR}:::xor --> z26:::output
pbn & mhs --> XOR75{XOR}:::xor --> z04:::output
pjv & bhn --> AND70{AND}:::and --> jnn
pjv & bhn --> XOR76{XOR}:::xor --> z05:::output
pnr & ghk --> AND71{AND}:::and --> kgf
pqv & kcv --> AND72{AND}:::and --> mnv
pwm & cjh --> AND73{AND}:::and --> nct
pwm & cjh --> XOR77{XOR}:::xor --> z20:::output

